
export enum UserRole {
  DIPLOMA = 'Diploma Student',
  UG = 'Undergraduate Student',
  RURAL = 'Rural Aspirant',
  GUEST = 'Guest',
  PG = 'Postgraduate Student'
}

export interface UserProfile {
  id: string;
  name: string;
  emailOrMobile: string;
  role: UserRole;
  method: 'email' | 'mobile' | 'google' | 'facebook' | 'github' | 'demo';
  isVerified: boolean;
  isNewUser?: boolean;
}

export interface StudentProfile {
  educationLevel: string;
  currentYear: string;
  stream: string;
  state: string;
  interest: string;
  gender: string;
  familyIncome: string;
}

export interface UserAction {
  id: string;
  title: string;
  description: string;
  link: string;
  status: 'Pending' | 'Done';
  isUrgent?: boolean;
  deadline?: string;
  isAutoGenerated?: boolean;
}

export interface Goal {
  id: string;
  title: string;
  description: string;
  actions: UserAction[];
}

export interface Scholarship {
  id: string;
  name: string;
  description: string;
  eligibilityExplanation: string;
  deadline: string;
  applyLink: string;
  docsNeeded: string[];
}

export interface Internship {
  id: string;
  title: string;
  organization: string;
  description: string;
  location: string;
  duration: string;
  stipend: string;
  link: string;
  type: 'Govt' | 'MNC' | 'Startup';
}

export interface Course {
  id: string;
  title: string;
  provider: 'SWAYAM' | 'Skill India' | 'Google' | 'Microsoft' | 'IBM' | 'NVIDIA' | 'IIT';
  category: 'IT' | 'Core' | 'Data' | 'AI' | 'Finance' | 'Soft Skills';
  education_level: 'Diploma' | 'UG' | 'PG' | 'All';
  link: string;
  is_new: boolean;
}

export interface Opportunity {
  id: string;
  title: string;
  type: 'Hackathon' | 'Internship' | 'Training' | 'Competition';
  provider: string;
  category: 'Tech' | 'Core' | 'Trading' | 'Finance' | 'Research';
  deadline: string;
  link: string;
  is_new: boolean;
}

export interface CourseStatus {
  courseId: string;
  status: 'Not Started' | 'In Progress' | 'Completed';
}

export interface ExternalPlatform {
  id: string;
  name: string;
  description: string;
  url: string;
  icon: string;
  category: string;
  isMNC?: boolean;
}

export interface SyncEvent {
  id: string;
  message: string;
  timestamp: string;
  type: 'course' | 'opportunity' | 'scholarship';
}

// Fixed missing type: InterviewQuestion
export interface InterviewQuestion {
  question: string;
  answer: string;
}

// Fixed missing type: AptitudeQuestion
export interface AptitudeQuestion {
  question: string;
  options: string[];
  correctIndex: number;
}
