
import { COURSE_DATABASE } from '../constants.js';

export const getRecommendedCourses = (profile) => {
  return COURSE_DATABASE.filter(c => c.education_level === 'All' || c.education_level === profile.educationLevel);
};

export const generateCourseActions = (recommended) => {
  return recommended.map(c => ({
    id: `a_course_${c.id}`,
    title: `Start ${c.title}`,
    description: `Provider: ${c.provider}`,
    link: c.link,
    status: 'Pending',
    isAutoGenerated: true
  }));
};
