
import { StudentProfile, Course, UserAction } from '../types';
import { COURSE_DATABASE } from '../constants';

export const getRecommendedCourses = (profile: StudentProfile): Course[] => {
  return COURSE_DATABASE.filter(course => {
    // Basic filter by education level
    const levelMatch = course.education_level === 'All' || course.education_level === profile.educationLevel;
    if (!levelMatch) return false;

    // Rule-based matching by interest
    if (profile.interest === 'IT' && ['IT', 'Data', 'AI', 'Soft Skills'].includes(course.category)) return true;
    if (profile.interest === 'Core' && ['Core', 'IT', 'Soft Skills'].includes(course.category)) return true;
    if (profile.interest === 'Business' && ['Soft Skills', 'IT'].includes(course.category)) return true;
    if (profile.interest === 'Govt Exams' && ['Soft Skills', 'IT'].includes(course.category)) return true;

    // Default match for early years
    if (parseInt(profile.currentYear) <= 1) return course.category === 'Soft Skills' || course.provider === 'Skill India';

    return false;
  });
};

export const generateCourseActions = (recommended: Course[]): UserAction[] => {
  return recommended.map(course => ({
    id: `a_course_${course.id}`,
    title: `Start ${course.title} on ${course.provider}`,
    description: `Begin your certified learning path in ${course.category}.`,
    link: course.link,
    status: 'Pending',
    isAutoGenerated: true
  }));
};
