
import { OPPORTUNITY_DATABASE } from '../constants.js';

export const getRecommendedOpportunities = (profile) => {
  return OPPORTUNITY_DATABASE.filter(o => o.is_new || profile.interest === o.category);
};

export const generateOpportunityActions = (recommended) => {
  return recommended.map(o => ({
    id: `a_opp_${o.id}`,
    title: `Apply for ${o.title}`,
    description: `Provider: ${o.provider}`,
    link: o.link,
    status: 'Pending',
    isAutoGenerated: true
  }));
};
