
import { StudentProfile, Opportunity, UserAction } from '../types';
import { OPPORTUNITY_DATABASE } from '../constants';

export const getRecommendedOpportunities = (profile: StudentProfile): Opportunity[] => {
  const year = parseInt(profile.currentYear);
  
  return OPPORTUNITY_DATABASE.filter(opp => {
    // IT Interest -> Tech category + Hackathons
    if (profile.interest === 'IT') {
      if (opp.category === 'Tech' || opp.type === 'Hackathon') return true;
    }

    // Finance/Business -> Trading/Finance
    if (profile.interest === 'Business' || profile.interest === 'Govt Exams') {
      if (opp.category === 'Trading' || opp.category === 'Finance') return true;
    }

    // Diploma/Core -> Core category + Training/Internships
    if (profile.educationLevel === 'Diploma' || profile.interest === 'Core') {
      if (opp.category === 'Core' || opp.type === 'Training' || opp.type === 'Internship') return true;
    }

    // Final Year -> Internships & Research
    if (year >= 4) {
      if (opp.type === 'Internship' || opp.category === 'Research') return true;
    }

    // New items always recommended for discovery
    if (opp.is_new) return true;

    return false;
  });
};

export const generateOpportunityActions = (recommended: Opportunity[]): UserAction[] => {
  const now = new Date();
  
  return recommended.map(opp => {
    const deadlineDate = new Date(opp.deadline);
    const diffDays = Math.ceil((deadlineDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
    
    return {
      id: `a_opp_${opp.id}`,
      title: `Apply for ${opp.title}`,
      description: `Target: ${opp.provider} • Deadline: ${opp.deadline}`,
      link: opp.link,
      status: 'Pending',
      isUrgent: diffDays <= 7 && diffDays >= 0,
      deadline: opp.deadline,
      isAutoGenerated: true
    };
  });
};
